services:
  - type: web
    name: linkedin-community-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://linkedin-community-backend.onrender.com 